### PR TITLE
Miscerrorlag

### PR DESCRIPTION
**Pull request by d97hah**

### CODE REVIEW

**Comment by xrotwang** [comment]
Good thing I'm gearing up for glottolog 3.5.

d97hah <notifications@github.com> schrieb am Mi., 29. Mai 2019, 17:24:

**Comment by xrotwang** [comment]
@d97hah something must have gone wrong here. E.g. there's a duplicate `daic1237` with identical `md.ini`:
```
$ diff languoids/tree/taik1256/kamt1241/daic1237/md.ini languoids/tree/taik1256/kamt1241/daic1237/nort3326/daic1237/md.ini
```

**Comment by d97hah** [comment]
Yes, I also see some glottolog check things, fixing

Pada tanggal Rab, 29 Mei 2019 pukul 20.25 Robert Forkel <
notifications@github.com> menulis:

**Comment by xrotwang** [comment]
The inner `daic1237` has only one child, so that's probably the "wrong" one:
```
    ├── daic1237
    │   ├── md.ini
    │   └── nort3180
    │       ├── md.ini
    │       ├── nort3189
    │       │   ├── bouy1240

```

**Comment by d97hah** [comment]
Ok @xrotwang, check now

**Comment by xrotwang** [comment]
Ok, there are a couple of errors regarding missing references, but I think I can take it from here. Will do so tomorrow.

**Comment by d97hah** [comment]
They've been fixed in master

Pada tanggal Kam, 30 Mei 2019 pukul 20.31 Robert Forkel <
notifications@github.com> menulis:

**Comment by xrotwang** [comment]
Yes, I noticed when merging `master`. Hopefully all is good now. At least `glottolog check` doesn't complain ...

**Pull request merged**
