### PR TITLE
Fix error in Tangkhulic misspecification

### PR DESCRIPTION
**Pull request by d97hah**

### CODE REVIEW

**Comment by xrotwang** [comment]
@d97hah is this serious enough to warrant a 3.3.2 release on http://glottolog.org ?

**Comment by d97hah** [comment]
yes, either that or a soon 3.4 so people will not have time to notice!?

Pada tanggal Jum, 17 Agt 2018 pukul 14.56 Robert Forkel <
notifications@github.com> menulis:

**Comment by xrotwang** [comment]
@d97hah do you have any other biggish changes that would make a 3.4 more reasonable? Technically, a bug fix release requires as much effort as a 3.4, so I'd prefer a 3.4, but it should have a bit more content.

**Comment by d97hah** [comment]
No, no immediate biggish changes so then 3.3.2 is preferrable

Pada tanggal Jum, 17 Agt 2018 pukul 15.30 Robert Forkel <
notifications@github.com> menulis:

**Comment by xrotwang** [comment]
ok

**Comment by xrotwang** [comment]
lesson to learn is - I guess - smaller PRs :)

**Pull request merged**
