### PR TITLE
Mirndifix

### PR DESCRIPTION
**Pull request by d97hah**

### CODE REVIEW

**Comment by xflr6** [comment]
This adds 3515 new `isbn` fields to `hh.bib` with some inconsistency regarding the delimiter(s?).
About around 1900 like this (comma separated):
```
@book{g:MacDonell:Sanskrit,
    isbn = {0198154666, 9780198154662},
```
But also around 1500 with different formats (one or two spaces, spaces but also commas, duplication?):
```
@book{s:Mahmood:Kelantan,
    isbn = {9836239413 9789836239419},
@book{g:Abeghian:Neuarmenische,
    isbn = {1306296374  9781306296373},
@book{hv:Agard:Romance,
   isbn = {0878400885  9780878400881  0878400893  9780878400898, 0878400893 9780878400898},
@book{d:Hindley:Old-French,
    isbn = {0521345642  9780521345644, 0521345642 9780521345644},
@book{g:Valdman:Haitian,
    isbn = {9780884323747 : PAP 0884323749 : PAP},
```
Also around 80 entries like this (at least some of them already in the current version though):
```
@book{soc:Berjaoui:Moroccan,
    isbn = {ISBN 978-3-89586-179-6}
@book{typ:Besha:Shambala:1989,
    isbn = {ISBN-10 3-496-00482-7},
@book{el:NettleRomaine,
    isbn = {0195136241  9780195136241  0195152468  9780195152463, ISBN-0-19-513624-1},
```
If we want to parse the `isbn` field, this probably needs to be standardized.

```$ glottolog check``` shows some warnings checking the new tree (retirements, missing new codes) but nothing new when comparing to the current version, so I assume they can be ignored for now.

**Comment by d97hah** [comment]
The isbn's are grabbed from worldcat where this information is differently
delimited indeed. Seems the different format are few enough to
autostandardize so then one of us to do it with some code gets a medal.

The glottolog check tree thigs that remain are pending (or retired codes in
bookkeeping, which IMHO requires no action and shouldn't give a warning).

2017-10-10 11:12 GMT+02:00 Sebastian Bank <notifications@github.com>:

**Comment by xflr6** [comment]
> Seems the different format are few enough to autostandardize so then one of us to do it with some code
Having a look at this branching from your PR.

**Comment by xflr6** [comment]
PTAL at the script added in 16c2d4756a56b189d1ee5e62ea1b4269ba8e8f9d:
* `', '` as delimiter, no isbn hyphen formatting
* assumes that we only want isbn-13 (convert, drop)
* includes some manual changes, are these okay? https://github.com/clld/glottolog/blob/16c2d4756a56b189d1ee5e62ea1b4269ba8e8f9d/scripts/fix_isbn.py#L27-L37

**Comment by d97hah** [comment]
Thanks, just pushed a new hh.bib to mirndifix which went through a pass of
fix_isbn.py

2017-10-10 17:13 GMT+02:00 Sebastian Bank <notifications@github.com>:

**Pull request merged**
