### PR TITLE
Lendu dialects + Musgu position and dialects + Xamtanga dialects + Zi…

### PR DESCRIPTION
**Pull request by d97hah**
…gula-Mushungulu merger + Bataic clf fix + new hh.bib + coordinates from Hedvig

### CODE REVIEW

**Comment by xrotwang** [comment]
hm. something seems wrong. 36 new glottocodes have been assigned - but I see only 24 new languoid files. Will investigate.

**Comment by xrotwang** [comment]
So glottolog check gives me this ERROR:
```
ERROR   ziw: duplicate hid
languoids/tree/atla1278/volt1241/benu1247/bant1294/sout3152/narr1281/east2731/nort3203/nort3209/ruvu1235/west2846/seut1234/zigu1243/zigu1244/zigu1242
languoids/tree/atla1278/volt1241/benu1247/bant1294/sout3152/narr1281/east2731/nort3203/nort3209/ruvu1235/west2846/seut1234/zigu1243/zigu1244
```

Did strange things happen during the creation of this PR?

**Comment by xrotwang** [comment]
I think I found the problem: The new glottocode [bale1256](https://github.com/clld/glottolog/blob/a7c522d18dfb95cd6489b371ee9c51ccb1fc317c/languoids/tree/cent2225/lend1246/bale1256/md.ini) seems to be identical to the superseded [bale1255](https://github.com/clld/glottolog/blob/master/languoids/tree/cent2225/lend1246/bale1255/md.ini). Is it possible that you removed parts of the tree by hand in th middle of the process of creating the new tree?

**Comment by d97hah** [comment]
No, but I might have run lff2tree once, then forgot about it, and then run
it again. What's the easiest way to fix? checkout languoids from master and
re-run? [ziw] shouldn't be there for zigu1242 (the removal in lff/dff
doesn't seem to always carry over). Sorry for once again forgetting to run
glottolog check

Pada tanggal Jum, 15 Mar 2019 pukul 18.26 Robert Forkel <
notifications@github.com> menulis:

**Comment by d97hah** [comment]
The error is I forgot to do tree2lff after the last round. Hopefully now a series of fixes took care of this. I realise a git squash is needed here but I am too novice to perform it...

**Pull request merged**
