### PR TITLE
Updated dialect inventory of Romani varieties

### PR DESCRIPTION
**Pull request by d97hah**

### CODE REVIEW

**Comment by xrotwang** [comment]
@d97hah does this help us to fill these in: https://github.com/lexibank/diacl/blob/master/etc/languages.csv#L20-L37 ?

**Comment by xrotwang** [comment]
@d97hah ah, I already see that yes, it does help. I think I can map by name - unless you think there might be complications that I'm missing.

**Comment by d97hah** [comment]
Did you mean to write that to someone else?

Pada tanggal Rab, 22 Mei 2019 pukul 08.54 Robert Forkel <
notifications@github.com> menulis:

**Comment by xrotwang** [comment]
No, it was a followup to my question whether the Romani dialects in the lexibank DIACL dataset can now be mapped better - see https://github.com/lexibank/diacl/issues/6

**Comment by d97hah** [comment]
Ah sorry didn't see that. Yes you can map by name, Dolenjski
is Slovenian-Croatian Romani [slov1272]. Let me know if you have any
problems, I'll fix.

Pada tanggal Rab, 22 Mei 2019 pukul 11.35 Robert Forkel <
notifications@github.com> menulis:

**Pull request merged**
