### PR TITLE
Added Cantabrian and misc other small things

### PR DESCRIPTION
**Pull request by d97hah**

### CODE REVIEW

**Comment by d97hah** [comment]
Wow, when trying to resolve this conflict I got git to segfault!

C:\Python27\glottolog>git pull --rebase origin cantabrian
From https://github.com/clld/glottolog
 * branch                  cantabrian -> FETCH_HEAD
First, rewinding head to replay your work on top of it...
Applying: lgcode altnames in altnames section
.git/rebase-apply/patch:9: trailing whitespace.
hhbib_lgcode =
.git/rebase-apply/patch:22: trailing whitespace.
hhbib_lgcode =
.git/rebase-apply/patch:42: trailing whitespace.
hhbib_lgcode =
.git/rebase-apply/patch:55: trailing whitespace.
hhbib_lgcode =
.git/rebase-apply/patch:70: trailing whitespace.
hhbib_lgcode =
/mingw64/libexec/git-core/git-rebase--am: line 16:  7608 Segmentation fault      git am $git_am_opt --rebasing --resolvemsg="$resolvemsg" ${gpg_sign_opt:+"$gpg_sign_opt"} < "$GIT_DIR/rebased-patches"

**Comment by d97hah** [comment]
Ok I need professional help here, the conflicting files don't exist in my branch, so they're hard to fix!?

**Comment by xflr6** [comment]
Try this branch (I just rebased your branch onto master, the two renamed files reported as conflicting here seem to be correct, i.e. they still contain the hhbib_altnames but mabe take a closer look): https://github.com/clld/glottolog/compare/cantabrian-fix

**Comment by xflr6** [comment]
It should be possible to hard-reset `cantabrian` to the commit in `cantabrian-fix` and then force-push to update the PR.

**Comment by d97hah** [comment]
Ok looks good, can you just merge it to master and then I go from there?

2017-11-17 14:34 GMT+01:00 Sebastian Bank <notifications@github.com>:

**Comment by xrotwang** [comment]
Congrats!

Am 17.11.2017 14:58 schrieb "Sebastian Bank" <notifications@github.com>:

**Pull request merged**
