### PR TITLE
Added coordinates for sign languages

### PR DESCRIPTION
**Pull request by borstell**
Manually added coordinates for sign languages. Includes some languages not found in Glottolog as well as "dialects" and old Glottocodes.

### CODE REVIEW

**Comment by xrotwang** [comment]
@d97hah can you have a look at https://github.com/clld/glottolog/pull/338/files and see what can be incorporated?

**Comment by d97hah** [comment]
Thanks so much Calle! I'll add these coordinates in their respective
places. Thanks also
for alerting me to the four recently "discovered" sign lgs not in
Glottolog. Just one question
re what you call Douentza Sign Language.  In the Nyst, Sylla & Magassouba
2012 paper, all that is said is that a lot
of signers in and around Douentza were recorded and potentially these could
be signers of the same or different varieties which could or could not the
same sign languages as other already present in e.g. Glottolog. Is it now
known that there is at least one 'Douentza Sign Language' different from
all other known sign languages? Appx how many signers? Is it known to be
related to another sign language or is it a presumed village descended
isolate? all the best,H

ps. Possibly this paper has the answer but the link to the pdf is broken:

"Introduction: The time-depth and typology of rural sign languages"

https://pure.mpg.de/pubman/item/item_2543540_3/component/file_2543539/DeVos&Nyst_inpress_IntroductionThetime-depthandtypologyofruralsignlanguages.pdf


Pada tanggal Sen, 1 Apr 2019 pukul 02.23 Carl Börstell <
notifications@github.com> menulis:

**Comment by xrotwang** [comment]
Link works for me - but my browser replaces the `&` with `%26`

**Comment by d97hah** [comment]
Then email me the pdf because none of my browsers get it even with manual
replacement of the & (I get internal server error back from pure.mpg.de)

Pada tanggal Sen, 1 Apr 2019 pukul 13.01 Robert Forkel <
notifications@github.com> menulis:

**Comment by xrotwang** [comment]
Already did. Send me the URL that got internal server error. Will forward
to the mpdl people.

d97hah <notifications@github.com> schrieb am Mo., 1. Apr. 2019, 13:27:

**Comment by xrotwang** [comment]
see https://github.com/clld/glottolog/pull/342

**Comment by borstell** [comment]
> Thanks so much Calle! I'll add these coordinates in their respective places. Thanks also for alerting me to the four recently "discovered" sign lgs not in Glottolog. Just one question re what you call Douentza Sign Language. In the Nyst, Sylla & Magassouba 2012 paper, all that is said is that a lot of signers in and around Douentza were recorded and potentially these could be signers of the same or different varieties which could or could not the same sign languages as other already present in e.g. Glottolog. Is it now known that there is at least one 'Douentza Sign Language' different from all other known sign languages? Appx how many signers? Is it known to be related to another sign language or is it a presumed village descended isolate? all the best,H ps. Possibly this paper has the answer but the link to the pdf is broken: "Introduction: The time-depth and typology of rural sign languages" https://pure.mpg.de/pubman/item/item_2543540_3/component/file_2543539/DeVos&Nyst_inpress_IntroductionThetime-depthandtypologyofruralsignlanguages.pdf Pada tanggal Sen, 1 Apr 2019 pukul 02.23 Carl Börstell < notifications@github.com> menulis:
> […](#)

I had updated coordinates on a few older downloads from Glottolog, which explains some older glottocodes in there. Some coordinates may have been changed although already present in Glottolog 3.3 – e.g. Finland-Swedish Sign Language which should be in Borgå/Porvoo as this was the location of their only Deaf school.

The village sign languages were added based on that very same De Vos & Nyst paper, also in consultation with Connie, but I myself don't know the details about the status of those newly added languages. This paper and others in the same special issue it introduced should provide the answers.

**Comment by d97hah** [comment]
That paper by De Vos & Nyst says Douentza SLs with an -s at the end, in
contrast to the others, suggesting there are more than one there. I've
emailed Veronica for a clarification....

Pada tanggal Sen, 1 Apr 2019 pukul 18.02 Carl Börstell <
notifications@github.com> menulis:

**Pull request closed without merging**
