### PR TITLE
Ethnologue has Maket as ISO code bjp

### PR DESCRIPTION
**Pull request by SimonGreenhill**

### CODE REVIEW

**Comment by xrotwang** [comment]
We have the language with the ISO code from which `bjp` was split: [Tangga](https://github.com/clld/glottolog/blob/master/languoids/tree/aust1307/nucl1752/mala1545/cent2237/east2712/ocea1241/west2818/meso1253/newi1242/stge1234/tang1348/md.ini). So the question is, can we assign the other two codes Niwer Mil `hrc`, and Warwar Feni `hrw` to the other two children of Tangga:
```
   └─ Tangga [tang1348]
                   ├─ Anir [anir1237]
                   ├─ Maket [make1251]
                   └─ Tanga [tang1349]
```

**Comment by d97hah** [comment]
Thanks, it's based on an unpublished survey so it's not yet implemented in
Glottolog (until the survey appears) but I've added the links to the iso:s
for the corresponding dialects at least, but for next version. all the
best, H

2017-07-05 11:48 GMT+02:00 Simon J Greenhill <notifications@github.com>:

**Comment by xrotwang** [comment]
@d97hah are you going to push these changes, though? If so, just close this PR.

**Comment by d97hah** [comment]
Yes, my lff2tree is running will push when done. And figure our how to
close this PR.

2017-07-05 12:32 GMT+02:00 Robert Forkel <notifications@github.com>:

**Comment by SimonGreenhill** [comment]
closed 👍

**Pull request closed without merging**
