### PR TITLE
complete hh_ethnologue_comment removal

### PR DESCRIPTION
**Pull request by xflr6**
see https://github.com/clld/glottolog/commit/cf0ecf5ddeabf9c8dd0199d695518bd395027dae#diff-2f18bf3164d6c669d84a297a0e2892f4 (#105)

### CODE REVIEW

**Comment by d97hah** [comment]
The comment about Siberian and Kazan Tatar being intelligible should be removed (I spoke to an expert who overruled the citation). But the hid should indeed be [sty].

**Comment by xflr6** [comment]
Allright, thanks. The removal of the `[hh_ethnologue_comment]` was not intended, right (the `isohid`, `comment_type` and `ethnologue_versions` fields currently belong to `core`)?

**Comment by xflr6** [comment]
Hm, I guess the whole section should be removed then?

**Comment by d97hah** [comment]
Yes whole section removed

2017-11-27 10:00 GMT+01:00 Sebastian Bank <notifications@github.com>:

**Comment by xflr6** [comment]
Okay, updated accordingly, merging.

**Pull request merged**
