### PR TITLE
normalize references gbid field, fixes clld/glottolog3#77

### PR DESCRIPTION
**Pull request by xflr6**

### CODE REVIEW

**Comment by d97hah** [comment]
Good let me fix the gbid:s in my hh.bib and my script to grab them too.

**Comment by xflr6** [comment]
Sure, I think you can just push your latest `hh.bib` to master so we can rerun `scripts/fix_gbid.py` on it (I can update the PR then).

**Comment by d97hah** [comment]
Ok I am trying to be a git guru so I pushed to the gbid branch, did it work?

2017-11-24 13:30 GMT+01:00 Sebastian Bank <notifications@github.com>:

**Comment by xflr6** [comment]
Thanks. To facilitate comparison, I squashed your two commits into one here: https://github.com/clld/glottolog/compare/gbid-squash

Just to be on the safe side: It drops over 4000 `glottolog_ref_id` fields (and also changes some, also to lower ids), is this intended here?

AFAICT, it also contains a handful of regressions with respect to `gbid`:
```shell
$ grep '^[+-]' 0001-real-fix-to-hh.bib-update-to-hh.bib.patch | grep gbid ol
-    gbid = {CiDOMgEACAAJ},
+    gbid = {http://www.google.com/books/feeds/volumes/CiDOMgEACAAJ},
-    gbid = {3RIMuwAACAAJ},
+    gbid = {http://www.google.com/books/feeds/volumes/3RIMuwAACAAJ},
-    gbid = {wyIuAAAAMAAJ},
+    gbid = {http://www.google.com/books/feeds/volumes/wyIuAAAAMAAJ},
-    gbid = {zcpkAAAAMAAJ},
+    gbid = {http://www.google.com/books/feeds/volumes/zcpkAAAAMAAJ},
-    gbid = {iFkOAAAAYAAJ},
+    gbid = {http://www.google.com/books/feeds/volumes/iFkOAAAAYAAJ},
-    gbid = {K99JNQAACAAJ},
+    gbid = {http://www.google.com/books/feeds/volumes/K99JNQAACAAJ},
-    gbid = {uFE9AAAAIAAJ},
+    gbid = {http://www.google.com/books/feeds/volumes/uFE9AAAAIAAJ},
```

**Comment by d97hah** [comment]
Let me fix those things (neither intended)

2017-11-24 14:46 GMT+01:00 Sebastian Bank <notifications@github.com>:

**Comment by d97hah** [comment]
Ok what about now?

2017-11-24 14:50 GMT+01:00 Harald Hammarström <harald.hammarstrom@gmail.com>
:

**Comment by xflr6** [comment]
Looks good, again squashed the three together in `gbid-squash`: One last thing is the removal of the header line with the encoding: https://github.com/clld/glottolog/commit/3c7a1f0cdb517224f85edf3e3699e483650beabf#diff-da217050127f79815921cdbdd55502b4L1

**Comment by d97hah** [comment]
Oops, I do want to have that there. Now pushed. One day I would like to
learn how to squash

2017-11-24 15:37 GMT+01:00 Sebastian Bank <notifications@github.com>:

**Comment by xflr6** [comment]
Thanks, squashed and force-pushed here, merging (let's have a git user group :).

**Pull request merged**
