### PR TITLE
Kahlupdates

### PR DESCRIPTION
**Pull request by d97hah**

### CODE REVIEW

**Comment by xrotwang** [comment]
hm. is there a chance you re-do this PR now that the other one is merged? The conflicts in `glottocodes.json` mean that conflicting glottocodes have been assinged - i.e. the same glottocode has been assigned to one new languoid in the Caledonian PR and to another one in this PR.

**Comment by xrotwang** [comment]
ok, wait a minute. I'll assess how hard the merging would be. Seems that only two glottocodes are affected.

**Comment by d97hah** [comment]
yes I am working on it but git is not immediately collaborative. Simplest
must be:
1. checkout current master (i.e with new caledonian merged)
2. stash changes in references/
3. kill hahlupdates
4. checkout new branch kahlupdatesnew
5. rerun lff2tree
6. push & pr

agree?


Pada tanggal Sel, 27 Nov 2018 pukul 10.06 Robert Forkel <
notifications@github.com> menulis:

**Comment by d97hah** [comment]
ok thx, I'll sit back until you push

Pada tanggal Sel, 27 Nov 2018 pukul 10.24 Robert Forkel <
notifications@github.com> menulis:

**Comment by xrotwang** [comment]
Sorry, I think you have to pull through with your plan. The problem here is, that the PRs are too much intertwined: The new PR adds classification comments to files that have been moved around in the old PR. I think I can't fix this easily.

**Pull request closed without merging**
