### PR TITLE
Chinamorehead

### PR DESCRIPTION
**Pull request by d97hah**

### CODE REVIEW

**Comment by xrotwang** [comment]
Hm. There seem to be quite a few spurious changes in this PR. I will have to investigate a bit, how that happened; in particular why the wrapping of long classification comments got lost.

In parallel, I'll push a couple more commits to this PR, fixing these problems ad hoc.

**Comment by d97hah** [comment]
Yes I saw trhat (= line warpping differences) but they are not harmful, I
thought. I blame the l.cfg.set function in API which should wrap lines as
required?!

Unrelated to teh PR I wanted to delete two languoids directly on the master
branch using the github UI but I could not figure out how to delete
directiores there so some unrest may have resulted (the net result is
supposed to be that only eastern and western remain as dialects of
Koromfe).

2017-03-06 8:45 GMT+01:00 Robert Forkel <notifications@github.com>:

**Comment by xrotwang** [comment]
I think you are right in blaming `l.cfg.set`, will look into this. Deleting directories isn't necessary as git will ignore any empty directories. So once all files are deleted, job should be done.

**Comment by xrotwang** [comment]
@d97hah did you pull the family classification comments out of some other files? It seems quite a few things I fixed, (some TeX-isms like `\%` or `\Xcite` or `\emph`), crept back in.

**Comment by d97hah** [comment]
Yes, sorry, let me fix them back (easiest if you merge the current with
master and I'll checkout master and fix it from there, alternatively if you
tell me what git commands I need to fix it from your last commit). Is it
exhaustive if I fix all \ and ~:s related things or are there more?

2017-03-06 10:42 GMT+01:00 Robert Forkel <notifications@github.com>:

**Comment by xrotwang** [comment]
It's already fixed.

**Pull request merged**
