### PR TITLE
hhbibaltnames in a separate field altnames_lgcode

### PR DESCRIPTION
**Pull request by d97hah**

### CODE REVIEW

**Comment by xflr6** [comment]
Can we put the names into the `hhbib_lgcode` section under `altnames` (otherwise we would need to add extra handling for a new section that is not really different typewise from the other `altnames` we cover)?
```ini
[altnames]
hhbib_lgcode =
```
We can still bikeshed about the exact option name. :)

Please run `glottolog check`:
```python
ValueError: invalid ref: 619-633
```
This is still from `languoids/tree/baib1250/md.ini`:
```shell
$ diff master.csv hh.csv | grep -v lgcode_altnames,glottolog | grep "[<>]"
< baib1250,classification,familyrefs,2,"**hh:g:Honeyman:Momu**:6-10,619-633"
> baib1250,classification,familyrefs,2,**hh:g:Honeyman:Momu**:6-10
> baib1250,classification,familyrefs,3,619-633
< tuca1253/east2698/east2702/east2708/pisa1246/pisa1247/pisa1245,core,latitude,0,-1.34021
> tuca1253/east2698/east2702/east2708/pisa1246/pisa1247/pisa1245,core,latitude,0,1.1017
< tuca1253/east2698/east2702/east2708/pisa1246/pisa1247/pisa1245,core,longitude,0,-69.662
> tuca1253/east2698/east2702/east2708/pisa1246/pisa1247/pisa1245,core,longitude,0,-70.502483
```
Note that this was actually already fixed where you branch off in `master` by 53b46c48efdcf2558fb152349aa9ec15cb743bcc (i.e. you still might not have the latest version): https://github.com/clld/glottolog/blob/4636c1305d53ad314d2e4a61a2fcc73d420e9aa2/languoids/tree/baib1250/md.ini#L10

**Comment by xflr6** [comment]
If you are too busy, we can probably also just branch off your PR and do the move/fix.

**Comment by d97hah** [comment]
Ok fixed. Afaik the Pisamora coordinate is correct as now pushed (wrong in
last master) or am I missing sthng?

2017-11-17 11:42 GMT+01:00 Sebastian Bank <notifications@github.com>:

**Comment by xflr6** [comment]
Yes, AFAIK we already made sure that that change is intended (left the full non-lgcode diff in here for reference as Github does not show everything). One could in principle do it in a separate commit but I think we are fine here.

**Comment by xflr6** [comment]
superseded by #153

**Pull request closed without merging**
