### PR TITLE
hhisocomment

### PR DESCRIPTION
**Pull request by d97hah**
Ok so 800 hh-comments (phew) are in.

* There's the comment field which is freetext with markdown (_emph_, |-| tables and <http://> urls). It may have cr:s that fuck up reading the .ini structure -- I am unsure about all that but at least I see no signs of parsing errors when readin the ini:s via pyglottolog.api

* There's the comment_type field which is either
-"spurious" meaning the comment is to explain why the languoid in question is spurious and in which Ethnologue (as below) that is/was 
-"missing" meaning the comment is to explain why the languoid in question is missing (as a language entry) and in which Ethnologue (as below) that is/was

* There's the "ethnologue_versions" field which says which Ethnologue version(s) from E16-E19 the comment pertains to, joined by /:s. E.g. E16/E17. In the case of comment_type=spurious, E16/E17 in the version field means that the code was spurious in E16/E17 but no longer spurious in E18/E19. In the case of comment_type=missing, E16/E17 would mean that the code was missing from E16/E17, but present in E18/E19. If the comment concerns a language where versions would be the empty string, instead the string ISO 639-3 appears. 

* There's the isohid field which says which iso/hid the comment concerns.

### CODE REVIEW

**Comment by xrotwang** [comment]
Running
```
(glottolog3)dlt5502178l:~/venvs/glottolog3/glottolog$ glottolog metadata
```
gives the below counts. Is the missing comment in one item something to worry about?

| section               | option                 |   count |
|:----------------------|:-----------------------|--------:|
| hh_ethnologue_comment |                        |       0 |
|                       | isohid                 |     820 |
|                       | comment_type           |     820 |
|                       | ethnologue_versions    |     820 |
|                       | comment                |     819 |

**Comment by d97hah** [comment]
Indeed I'll fix that shortly

2017-02-14 8:32 GMT+01:00 Robert Forkel <notifications@github.com>:

**Comment by xrotwang** [comment]
I pushed a couple of commits to master directly. So make sure to pull!

**Comment by d97hah** [comment]
Ok new lff2tree doesn't let me run until I fix a few dozen name clashes, so
I am doing that. They are 5 mins a piece.

2017-02-14 11:48 GMT+01:00 Robert Forkel <notifications@github.com>:

**Pull request merged**
