### PR TITLE
Tibetan dialect inventory updates with information from CDTD (Bielmei…

### LINKED ISSUE #308: Tibetan divisions
I don't know if it's the right place for this kind of request, but there is a comprehensive list of Tibetan dialects / languages in the following article: https://escholarship.org/uc/item/4qd7k36j on the very final page (Appendix C). There is also a map with some coordinates for the dialects on page 47. This seems like a very good source, could the data make it to Glottolog?

### PR DESCRIPTION
**Pull request by d97hah**
…er et al 2018)

closes #308

### CODE REVIEW

**Comment by xrotwang** [comment]
@d97hah do you remember who asked for including these?

**Comment by d97hah** [comment]
Elie Roux

Pada tanggal Kam, 21 Feb 2019 pukul 15.56 Robert Forkel <
notifications@github.com> menulis:

**Comment by xrotwang** [comment]
Ah, right. Do you think this covers more of the un-identified varieties in @bambooforest's PHOIBLE inventories?

**Comment by d97hah** [comment]
Yes but only so that they get more specific glottocodes. The ones I
suggested in the last email to Steve do just as well on a slightly higher
level. all the best, H

Pada tanggal Kam, 21 Feb 2019 pukul 16.10 Robert Forkel <
notifications@github.com> menulis:

**Comment by xrotwang** [comment]
ok

**Comment by d97hah** [comment]
Can you systematicallly merge when you approve? (It tends to get forgotten
otherwise)

Pada tanggal Kam, 21 Feb 2019 pukul 16.38 Robert Forkel <
notifications@github.com> menulis:

**Comment by xrotwang** [comment]
Ok. Will do. The one who merges is assigned as the one closing issues (if mentioned), though. So if I merge, GitHub will see you as lazier than you are :)

**Comment by d97hah** [comment]
Yes I am that lazy :-)

Pada tanggal Kam, 21 Feb 2019 pukul 17.06 Robert Forkel <
notifications@github.com> menulis:

**Pull request merged**
